version: '3.8'

services:
  babar:
    build: .
    volumes:
      - .:/app
      - ~/.babar:/root/.babar
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=${DEBUG:-false}
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama-init:
        condition: service_completed_successfully

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - '11434:11434'
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama-init:
    image: curlimages/curl:latest
    depends_on:
      ollama:
        condition: service_healthy
    command: ["sh", "-c", "curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"llama2\"}'"]

volumes:
  ollama_data:
